name: Build and publish container images
on: push
#  release:
#    types: [published]

env:
  REGISTRY_REPOSITORY: ghcr.io/konstantinblaesi
  REGISTRY_IMAGE: yasdi

jobs:
  build-and-publish:
    name: Build and publish container image
    strategy:
      matrix:
        arch: [amd64, arm64]
        containerFile: [alpine, debian]
    runs-on: ubuntu-latest
    environment: github container registry

    steps:
      - uses: actions/checkout@v2

      - name: Install qemu
        if: ${{ matrix.arch == 'arm64' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REGISTRY_IMAGE }}
          tags: latest ${{ github.ref  }}
          archs: ${{ matrix.arch }}
          containerfiles: |
            ./container/${{ matrix.containerFile }}.Containerfile

      - name: Publish image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY_REPOSITORY }}
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}
