name: Build and publish container images
on: [push]

env:
  REGISTRY_REPOSITORY: ghcr.io/konstantinblaesi
  REGISTRY_IMAGE: yasdi

jobs:
  build:
    name: Build container image
    strategy:
      matrix:
        arch: [amd64, arm64]
        containerFile: [alpine, debian]
    runs-on: ubuntu-latest
    environment: github container registry

    steps:
      - uses: actions/checkout@v2

      - name: Install qemu
        if: ${{ matrix.arch == 'arm64' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Set short commit sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REGISTRY_IMAGE }}
          tags: ${{ matrix.arch }}-latest ${{ matrix.arch }}-${{ steps.vars.outputs.sha_short }}
          archs: ${{ matrix.arch }}
          containerfiles: |
            ./container/${{ matrix.containerFile }}.Containerfile

      - name: Publish image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY_REPOSITORY }}
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
