name: Build Image using Containerfile
on: [push]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: yasdi
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./container/alpine.Containerfile
