name: Build Image using Containerfile
on: [push]

env:
  REGISTRY_USER: quayuser
  IMAGE_REGISTRY: quay.io
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  build-and-publish-image:
    name: Build and publish image
    runs-on: ubuntu-latest
    environment: github container registry

    steps:
      - uses: actions/checkout@v2

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: yasdi
          tags: latest ${{ github.sha }}
          archs: amd64, arm64
          containerfiles: |
            ./container/alpine.Containerfile

      - name: Publish image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/konstantinblaesi
          username: konstantinblaesi
          password: ${{ secrets.GHCR_TOKEN }}
